import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.min.css'
import './global.css'

export const metadata: Metadata = {
  title: 'syun560 page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return(
    <html lang="ja">
      <body>
        <main className="container shadow text-light pt-2">
          {children}
        </main>
      </body>
    </html>
  )
}
